.PHONY: docker_down docker_up containers proto build


docker_down:
	docker-compose stop
	docker-compose down
	docker rmi server

docker_up:
	docker-compose up

containers:
	docker ps -a

proto:
	protoc --proto_path=./pb/ \
		--go_out=./pb \
		--go_opt=paths=source_relative \
		--go-grpc_out=./pb \
		--go-grpc_opt=paths=source_relative \
		./pb/keykeep.proto

BINARY_NAME=key_keeper
BUILD_DIR=build
VERSION=0.1.0
SOURCE_DIR=./cmd/agent/

build:
	GOOS=windows GOARCH=amd64 go build -o $(BUILD_DIR)/$(BINARY_NAME)_$(VERSION)_windows_amd64.exe $(SOURCE_DIR)
	GOOS=darwin GOARCH=amd64 go build -o $(BUILD_DIR)/$(BINARY_NAME)_$(VERSION)_darwin_amd64 $(SOURCE_DIR)
	GOOS=linux GOARCH=amd64 go build -o $(BUILD_DIR)/$(BINARY_NAME)_$(VERSION)_linux_amd64 $(SOURCE_DIR)