.PHONY:


docker_down:
	docker-compose stop
	docker-compose down
	docker rmi server

docker_up:
	docker-compose up

containers:
	docker ps -a

proto:
	protoc --proto_path=./pb/ \
		--go_out=./pb \
		--go_opt=paths=source_relative \
		--go-grpc_out=./pb \
		--go-grpc_opt=paths=source_relative \
		./pb/keykeep.proto
